using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Catharsis.Generators
{
    /// <summary>
    /// Generates <c>INotifyPropertyChanged</c> properties. Mark a <c>partial</c> class with
    /// <c>[Catharsis.Generators.AutoNotify]</c> and each of its instance fields gets a public property that raises
    /// <c>PropertyChanged</c> when the value actually changes. A field <c>_name</c> (or <c>name</c>) becomes
    /// <c>Name</c>. The attribute is emitted into the consuming compilation, so nothing but this analyzer is referenced.
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class AutoNotifyGenerator : IIncrementalGenerator
    {
        internal const string AttributeMetadataName = "Catharsis.Generators.AutoNotifyAttribute";

        internal static readonly DiagnosticDescriptor NotPartial = new DiagnosticDescriptor(
            "CATGEN001", "AutoNotify class must be partial", "Class '{0}' is marked [AutoNotify] but is not declared partial",
            "Catharsis.Generators", DiagnosticSeverity.Error, isEnabledByDefault: true);

        internal static readonly DiagnosticDescriptor Unsupported = new DiagnosticDescriptor(
            "CATGEN002", "AutoNotify class is not supported", "Class '{0}' must be a top-level, non-generic class to use [AutoNotify]",
            "Catharsis.Generators", DiagnosticSeverity.Error, isEnabledByDefault: true);

        internal static readonly DiagnosticDescriptor NameCollision = new DiagnosticDescriptor(
            "CATGEN003", "AutoNotify property name collision", "Field '{0}' would generate a property that already exists on the type",
            "Catharsis.Generators", DiagnosticSeverity.Warning, isEnabledByDefault: true);

        private const string AttributeSource = @"// <auto-generated/>
#nullable enable
namespace Catharsis.Generators
{
    /// <summary>Asks the Catharsis source generator to create notifying properties for this class's fields.</summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    internal sealed class AutoNotifyAttribute : global::System.Attribute
    {
    }
}
";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterPostInitializationOutput(static ctx => ctx.AddSource("AutoNotifyAttribute.g.cs", AttributeSource));

            IncrementalValuesProvider<AutoNotifyModel> models = context.SyntaxProvider.ForAttributeWithMetadataName(
                AttributeMetadataName,
                static (node, _) => node is ClassDeclarationSyntax,
                static (ctx, ct) => BuildModel(ctx, ct));

            context.RegisterSourceOutput(models, static (ctx, model) =>
            {
                if (model.Diagnostic is GeneratorDiagnostic diagnostic)
                {
                    ctx.ReportDiagnostic(diagnostic.ToDiagnostic(DescriptorFor(diagnostic.Id)));
                }

                foreach (GeneratorDiagnostic warning in model.Warnings)
                {
                    ctx.ReportDiagnostic(warning.ToDiagnostic(NameCollision));
                }

                if (model.Source is string source)
                {
                    ctx.AddSource(model.HintName, source);
                }
            });
        }

        private static DiagnosticDescriptor DescriptorFor(string id) => id == NotPartial.Id ? NotPartial : Unsupported;

        private static AutoNotifyModel BuildModel(GeneratorAttributeSyntaxContext ctx, CancellationToken ct)
        {
            INamedTypeSymbol type = (INamedTypeSymbol)ctx.TargetSymbol;
            ClassDeclarationSyntax syntax = (ClassDeclarationSyntax)ctx.TargetNode;
            string hint = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat).Replace("global::", string.Empty) + ".AutoNotify.g.cs";

            if (type.ContainingType != null || type.IsGenericType)
            {
                return AutoNotifyModel.Failed(hint, GeneratorDiagnostic.Create(Unsupported.Id, type.Name, syntax.Identifier.GetLocation()));
            }

            if (!syntax.Modifiers.Any(static m => m.Text == "partial"))
            {
                return AutoNotifyModel.Failed(hint, GeneratorDiagnostic.Create(NotPartial.Id, type.Name, syntax.Identifier.GetLocation()));
            }

            HashSet<string> existing = new HashSet<string>(type.GetMembers().Select(static m => m.Name));
            List<string> members = new List<string>();
            List<GeneratorDiagnostic> warnings = new List<GeneratorDiagnostic>();

            foreach (IFieldSymbol field in type.GetMembers().OfType<IFieldSymbol>())
            {
                ct.ThrowIfCancellationRequested();

                if (field.IsStatic || field.IsConst || field.IsImplicitlyDeclared)
                {
                    continue;
                }

                string property = ToPropertyName(field.Name);

                if (property.Length == 0 || existing.Contains(property))
                {
                    warnings.Add(GeneratorDiagnostic.Create(NameCollision.Id, field.Name, field.Locations[0]));
                    continue;
                }

                string fieldType = field.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat.AddMiscellaneousOptions(SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier));
                members.Add($@"
        public {fieldType} {property}
        {{
            get => {field.Name};
            set
            {{
                if(!global::System.Collections.Generic.EqualityComparer<{fieldType}>.Default.Equals({field.Name}, value))
                {{
                    {field.Name} = value;
                    OnPropertyChanged(nameof({property}));
                }}
            }}
        }}
");
            }

            return AutoNotifyModel.Generated(hint, Render(type, members), [.. warnings]);
        }

        private static string ToPropertyName(string fieldName)
        {
            string trimmed = fieldName.TrimStart('_');

            if (trimmed.Length == 0)
            {
                return string.Empty;
            }

            string property = char.ToUpperInvariant(trimmed[0]) + trimmed.Substring(1);

            return property == fieldName ? string.Empty : property;
        }

        private static string Render(INamedTypeSymbol type, List<string> members)
        {
            StringBuilder builder = new StringBuilder();
            string ns = type.ContainingNamespace.IsGlobalNamespace ? string.Empty : type.ContainingNamespace.ToDisplayString();
            string indent = ns.Length == 0 ? string.Empty : "    ";
            string notifier = type.IsSealed ? "private" : "protected virtual";

            builder.AppendLine("// <auto-generated/>");
            builder.AppendLine("#nullable enable");

            if (ns.Length > 0)
            {
                builder.AppendLine("namespace " + ns);
                builder.AppendLine("{");
            }

            builder.AppendLine(indent + "partial class " + type.Name + " : global::System.ComponentModel.INotifyPropertyChanged");
            builder.AppendLine(indent + "{");
            builder.AppendLine("        public event global::System.ComponentModel.PropertyChangedEventHandler? PropertyChanged;");
            builder.AppendLine();
            builder.AppendLine("        " + notifier + " void OnPropertyChanged(string propertyName) => PropertyChanged?.Invoke(this, new global::System.ComponentModel.PropertyChangedEventArgs(propertyName));");

            foreach (string member in members)
            {
                builder.Append(member);
            }

            builder.AppendLine(indent + "}");

            if (ns.Length > 0)
            {
                builder.AppendLine("}");
            }

            return builder.ToString();
        }

        private sealed record AutoNotifyModel(string HintName, string? Source, GeneratorDiagnostic? Diagnostic, EquatableArray Warnings)
        {
            public static AutoNotifyModel Failed(string hint, GeneratorDiagnostic diagnostic) => new AutoNotifyModel(hint, null, diagnostic, EquatableArray.Empty);

            public static AutoNotifyModel Generated(string hint, string source, ImmutableArray<GeneratorDiagnostic> warnings) => new AutoNotifyModel(hint, source, null, new EquatableArray(warnings));
        }
    }
}
