using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Catharsis.Generators
{
    /// <summary>
    /// Generates fast, allocation-free enum helpers. Mark a top-level enum with
    /// <c>[Catharsis.Generators.EnumExtensions]</c> and a static <c>{Name}Extensions</c> class is emitted with
    /// <c>ToStringFast</c>, <c>TryParseFast</c> and <c>IsDefinedFast</c>. Each uses a <c>switch</c> over the enum's
    /// members, avoiding the reflection <c>Enum.ToString</c> and <c>Enum.TryParse</c> perform. For enums with several
    /// names for one value, <c>ToStringFast</c> returns the first declared name, as <c>Enum.ToString</c> commonly does.
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class EnumExtensionsGenerator : IIncrementalGenerator
    {
        internal const string AttributeMetadataName = "Catharsis.Generators.EnumExtensionsAttribute";

        internal static readonly DiagnosticDescriptor Unsupported = new DiagnosticDescriptor(
            "CATGEN004", "EnumExtensions enum is not supported", "Enum '{0}' must be a top-level enum to use [EnumExtensions]",
            "Catharsis.Generators", DiagnosticSeverity.Error, isEnabledByDefault: true);

        private const string AttributeSource = @"// <auto-generated/>
#nullable enable
namespace Catharsis.Generators
{
    /// <summary>Asks the Catharsis source generator to create fast helper methods for this enum.</summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Enum, AllowMultiple = false, Inherited = false)]
    internal sealed class EnumExtensionsAttribute : global::System.Attribute
    {
    }
}
";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterPostInitializationOutput(static ctx => ctx.AddSource("EnumExtensionsAttribute.g.cs", AttributeSource));

            IncrementalValuesProvider<EnumModel> models = context.SyntaxProvider.ForAttributeWithMetadataName(
                AttributeMetadataName,
                static (node, _) => node is EnumDeclarationSyntax,
                static (ctx, ct) => BuildModel(ctx, ct));

            context.RegisterSourceOutput(models, static (ctx, model) =>
            {
                if (model.Diagnostic is GeneratorDiagnostic diagnostic)
                {
                    ctx.ReportDiagnostic(diagnostic.ToDiagnostic(Unsupported));
                }

                if (model.Source is string source)
                {
                    ctx.AddSource(model.HintName, source);
                }
            });
        }

        private static EnumModel BuildModel(GeneratorAttributeSyntaxContext ctx, CancellationToken ct)
        {
            INamedTypeSymbol type = (INamedTypeSymbol)ctx.TargetSymbol;
            EnumDeclarationSyntax syntax = (EnumDeclarationSyntax)ctx.TargetNode;
            string hint = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat).Replace("global::", string.Empty) + ".EnumExtensions.g.cs";

            if (type.ContainingType != null)
            {
                return new EnumModel(hint, null, GeneratorDiagnostic.Create(Unsupported.Id, type.Name, syntax.Identifier.GetLocation()));
            }

            List<IFieldSymbol> members = [.. type.GetMembers().OfType<IFieldSymbol>().Where(static f => f.HasConstantValue)];
            ct.ThrowIfCancellationRequested();

            return new EnumModel(hint, Render(type, members), null);
        }

        private static string Render(INamedTypeSymbol type, List<IFieldSymbol> members)
        {
            string enumType = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            string ns = type.ContainingNamespace.IsGlobalNamespace ? string.Empty : type.ContainingNamespace.ToDisplayString();
            string accessibility = type.DeclaredAccessibility == Accessibility.Public ? "public" : "internal";
            string i = ns.Length == 0 ? string.Empty : "    ";
            StringBuilder b = new StringBuilder();

            b.AppendLine("// <auto-generated/>");
            b.AppendLine("#nullable enable");

            if (ns.Length > 0)
            {
                b.AppendLine("namespace " + ns);
                b.AppendLine("{");
            }

            b.AppendLine(i + accessibility + " static class " + type.Name + "Extensions");
            b.AppendLine(i + "{");

            b.AppendLine(i + "    /// <summary>Returns the name of the value without reflection, or its number if it is not a named member.</summary>");
            b.AppendLine(i + "    public static string ToStringFast(this " + enumType + " value)");
            b.AppendLine(i + "    {");
            b.AppendLine(i + "        switch(value)");
            b.AppendLine(i + "        {");

            HashSet<object> seen = new HashSet<object>();

            foreach (IFieldSymbol member in members)
            {
                if (seen.Add(member.ConstantValue!))
                {
                    b.AppendLine(i + "            case " + enumType + "." + Escape(member.Name) + ": return \"" + member.Name + "\";");
                }
            }

            b.AppendLine(i + "            default: return value.ToString();");
            b.AppendLine(i + "        }");
            b.AppendLine(i + "    }");
            b.AppendLine();

            b.AppendLine(i + "    /// <summary>Parses an exact, case-sensitive member name without reflection.</summary>");
            b.AppendLine(i + "    public static bool TryParseFast(string? name, out " + enumType + " value)");
            b.AppendLine(i + "    {");
            b.AppendLine(i + "        switch(name)");
            b.AppendLine(i + "        {");

            foreach (IFieldSymbol member in members)
            {
                b.AppendLine(i + "            case \"" + member.Name + "\": value = " + enumType + "." + Escape(member.Name) + "; return true;");
            }

            b.AppendLine(i + "            default: value = default; return false;");
            b.AppendLine(i + "        }");
            b.AppendLine(i + "    }");
            b.AppendLine();

            b.AppendLine(i + "    /// <summary>Determines whether the value is one of the enum's named members.</summary>");
            b.AppendLine(i + "    public static bool IsDefinedFast(this " + enumType + " value)");
            b.AppendLine(i + "    {");
            b.AppendLine(i + "        switch(value)");
            b.AppendLine(i + "        {");

            seen.Clear();

            foreach (IFieldSymbol member in members)
            {
                if (seen.Add(member.ConstantValue!))
                {
                    b.AppendLine(i + "            case " + enumType + "." + Escape(member.Name) + ":");
                }
            }

            b.AppendLine(i + "                return true;");
            b.AppendLine(i + "            default: return false;");
            b.AppendLine(i + "        }");
            b.AppendLine(i + "    }");
            b.AppendLine(i + "}");

            if (ns.Length > 0)
            {
                b.AppendLine("}");
            }

            return b.ToString();
        }

        private static string Escape(string identifier) =>
            Microsoft.CodeAnalysis.CSharp.SyntaxFacts.GetKeywordKind(identifier) != Microsoft.CodeAnalysis.CSharp.SyntaxKind.None ? "@" + identifier : identifier;

        private sealed record EnumModel(string HintName, string? Source, GeneratorDiagnostic? Diagnostic);
    }
}
