namespace Catharsis.Domain;

///<summary>
///A bindable view model for editing the customer-facing details of a draft <see cref="Order"/>. Its properties are
///generated by <c>[AutoNotify]</c> from the private fields, so each raises <c>PropertyChanged</c> only when the value
///actually changes.
///</summary>
[AutoNotify]
public sealed partial class OrderDraftViewModel
{
    #pragma warning disable IDE0044, CS0649 // Fields are read and written through the generated properties.
    private string _customerName = string.Empty;
    private string _notes = string.Empty;
    private bool _giftWrap;
    #pragma warning restore IDE0044, CS0649
}
